### ISSUE TITLE
Installing with Yarn isn't working

### ISSUE THREAD

**Issue by tferreira** [hero-guo/jsondiffpatch-for-react#2]
Hi,

I'm trying to install your package using `Yarn` but I'm having this error message (only with `jsondiffpatch-for-react`):

> yarn add jsondiffpatch-for-react
yarn add v1.2.1
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.npmjs.org/jsondiffpatch-for-react: tunneling socket could not be established, cause=write EPROTO 140735161225216:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:\n".

Any idea on what's happening? Thank you.

**Comment by hero-guo** [comment]
@tferreira hi guys, It could be a network problem。Try a few times more or use the nrm to replace npm registry

https://github.com/Pana/nrm

**Comment by tferreira** [comment]
You're right, sorry for this, issue came from a bad proxy conf inside the `.npmrc` file.
